language: rust
os: osx
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo fmt --all

rust:
  - stable
  - beta
jobs:
  fast_finish: true
  install:
    -rustup component add rustfmt
