language: rust
os: osx
# project is a workspace, so pass --all to test all member crates
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo fmt --all

rust:
  - stable
  - beta

# cache dependencies to only recomile if compiler is upgraded
cache: cargo

jobs:
  fast_finish: true
