[package]
name = "imp-p2p"
version = "0.1.0"
authors = ["jonny rhea <jonny.rhea@consensys.com>"]
edition = "2018"

[features]
default = ["mothra"]
local = ["mothra_local"]

[dependencies]
libp2p = "0.13.2"
eth2 = { path = "../../eth2", package="imp-eth2"}
types = { path = "../../types", package="imp-types"}
utils = { path = "../../utils", package="imp-utils"}
mothra = { git = "https://github.com/prrkl/mothra", branch = "master", package = "mothra", optional = true }
mothra_local = { path = "../../../mothra/core", package = "mothra", optional = true }

tokio-compat = { version = "0.1.5", features = ["rt-full"] }
tokio-01 = { version = "0.1.22", package = "tokio"}
tokio-02 = { version = "0.2", features = ["full"], package = "tokio" }
slog = { version = "2.5.2" , features = ["max_level_trace"] }
target_info = "0.1.0"
clap = "2.33.0"
futures-01 = { version = "0.1.29", package = "futures" }
futures = "0.3"
